on:
  pull_request:
  push:
    branches: [main, unstable]
  workflow_dispatch:

permissions: {}

jobs:
  nix-flake-check:
    name: nix-flake-check
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: determinatesystems/nix-installer-action@c5a866b6ab867e88becbed4467b93592bce69f8a # v21
      - run: |
          echo "Version: \`$(nix --version)\`" \
          | tee --append "${GITHUB_STEP_SUMMARY}"
      - run: |
          nix-shell --packages nix-info --run 'nix-info --markdown --sandbox --host-os' \
          | tee --append "${GITHUB_STEP_SUMMARY}"
      - run: |
          nix --experimental-features "nix-command flakes" flake check \
          | tee --append "${GITHUB_STEP_SUMMARY}"
